### ISSUE TITLE
AOT compilation error

### ISSUE THREAD

**Issue by BlueForeverI** [fetrarij/ngx-daterangepicker-material#79]
Hello, I am using v.1.3.0 with Angular 7 and works fine with a simple `ng-serve`, but when I build the application with `ng-build` and AOT enabled, it fails with the following error:

```
ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'weekdaysMin' was called in 'ɵb'
    'ɵb' calls 'weekdaysMin' at ../ngx-daterangepicker-material/ngx-daterangepicker-material.ts(24,17).
```

I import the picker module in my app module with NgxDaterangepickerMd.forRoot().

**Comment by lmbai** [comment]
it seem like `1.2.7` have the issue too

**Comment by georgiyolovski** [comment]
@lmbai works fine on my side with `1.2.7`. How do you import the module in your application module?

**Comment by lmbai** [comment]
> @lmbai works fine on my side with `1.2.7`. How do you import the module in your application module?

i import it with `NgxDaterangepickerMd.forRoot()`. 
but i didn't import it in the root module.   
i import it in a `CommonSharedModule` then import the `CommonSharedModule` in the `root module`..

should i import directly in the `root module`?

**Comment by georgiyolovski** [comment]
@lmbai you should import it with `NgxDaterangepickerMd` only, not with forRoot()

**Comment by lmbai** [comment]
@georgiyolovski  it doesn’t work.
Here is the case:
We have a `app.module.ts`
We have a sub module called `child.module.ts`
In side the `child.module.ts` we have several components , the `NgxDaterangepickMd` is used in one of the component. 

If I import it in the `child.module.ts` without the `forRoot’,  when we do the JIT Debug, it will will throw error “config”

If I import it in the `child.module.ta` with `forRoot`, it works fine with the JIT debug, but when we do a AOT compile , it will throw error as this ticket descriped .

**Comment by lmbai** [comment]
my bad, there is no `forRoot` in the `1.2.7` at all. i will try again tmr.

**Comment by fetrarij** [comment]
with 1.2.7 , it should work without forRoot().
I will fix for 1.3.0.
Thanks @georgiyolovski

**Comment by lmbai** [comment]
@georgiyolovski @fetrarij  Thanks a lot. 
confirmed that the `1.2.7` is working fine.

**Comment by Arunids** [comment]
I am also facing same issue, with version of 1.6.8, If i try to remove forRoot(), then issues getting : "Local config not defined", How to resolve this ??

**Comment by fetrarij** [comment]
@Arunids 1.6.8 ? there's no tag for that for now.
If you use version less than 1.3.0 use only: `NgxDaterangepickerMd`  if you use 1.3.0, use `NgxDaterangepickerMd.forRoot()`

**Comment by adapptadmin** [comment]
> TypeError: Cannot read property 'NaN' of undefined
>     at Object.updateRenderer

  this error after build --prod and and detail error on main.ts file

> `function CY(t) {
            return Fl(0, [(t()(),
            xs(0, 0, null, null, 1, null, null, null, null, null, null, null)), (t()(),
            jl(1, null, [" ", " ", " "]))], null, function(t, e) {
                var n = e.component;
                t(e, 1, 0, n.locale.monthNames[null == n.calendarVariables ? null : null == n.calendarVariables.left ? null : n.calendarVariables.left.calendar[1][1].month()], null == n.calendarVariables ? null : null == n.calendarVariables.left ? null : n.calendarVariables.left.calendar[1][1].format(" YYYY"))
            })
        }`

**Comment by adapptadmin** [comment]
above issues i got solution
`  localconfi: any = {
    applyLabel: 'ok',separator: ' To ', format: 'ddd, MMMM D, YYYY h:mm A',
    direction: 'ltr',
    weekLabel: 'W',
    cancelLabel: 'Cancel',
    customRangeLabel: 'Custom range',
    daysOfWeek: moment.weekdaysMin(),
    monthNames: moment.monthsShort(),
    firstDay: moment.localeData().firstDayOfWeek()
    };`

`<input matInput type="text" ngxDaterangepickerMd [(ngModel)]="selected" (ngModelChange)="datepickerChange($event)" 
                      [alwaysShowCalendars]="true" [ranges]="ranges" [showClearButton]="true"
                       [locale]="localconfi"  placeholder="Double Click for Date" class="form-control" required/>
                  </mat-form-field>`
`NgxDaterangepickerMd.forRoot({
      separator: ' To ', 
      applyLabel: 'Okay',
      format: 'ddd, MMMM D, YYYY h:mm A'
    })`

**Comment by ashokvarmauppalapati** [comment]
I was using 1.2.7 version without forRoot(), Until yesterday it was working fine. 
Suddenly getting no provider for LocalConfig! error. How to solve this??

**Comment by lmbai** [comment]
@ashokvarmauppalapati  hi , can u check your `package.json`?

If you a using `^1.2.7`. And run `npm install —force` accidentally, it may reinstall the `1.3.0`.

Just a gentle reminder, I made the same mistake a few days ago.
Better fix the version to `1.2.7`

**Comment by ashokvarmauppalapati** [comment]
@lmbai thank you.... ya it updated to 1.3.0 while updating npm.
