### ISSUE TITLE
ngModel does not seem to be working with angular 7.0.3

### ISSUE THREAD

**Issue by ranjitkumarsingh** [fetrarij/ngx-daterangepicker-material#139]
Hello,
I am using following inline settings with angular 7.0.3. Calendar is showing up properly however ngModel does not getting updated or reflected in calendar with initial value. Also change event is not working. 
 <ngx-daterangepicker-material
                [(ngModel)]="selected"
                [locale]="{applyLabel: 'Go'}"
                [timePicker]="true"
                [timePicker24Hour]="true"
                [timePickerSeconds]="true"
                (change)="selectedDateRangeChange($event)">
        </ngx-daterangepicker-material>

I am getting following error in console when calendar is showing up -
 
ERROR TypeError: dir.valueAccessor.writeValue is not a function
    at setUpControl (forms.js:1703)
    at NgModel.push../node_modules/@angular/forms/fesm5/forms.js.NgModel._setUpStandalone (forms.js:4231)
    at NgModel.push../node_modules/@angular/forms/fesm5/forms.js.NgModel._setUpControl (forms.js:4218)
    at NgModel.push../node_modules/@angular/forms/fesm5/forms.js.NgModel.ngOnChanges (forms.js:4178)
    at checkAndUpdateDirectiveInline (core.js:18616)
    at checkAndUpdateNodeInline (core.js:19884)
    at checkAndUpdateNode (core.js:19846)
    at debugCheckAndUpdateNode (core.js:20480)
    at debugCheckDirectivesFn (core.js:20440)
    at Object.eval [as updateDirectives] (TimeSelectionComponent.html:17)

**Comment by fetrarij** [comment]
hello @ranjitkumarsingh , You could not use ngModel directly with the inline mode, and the change event is not availabele, use choosedDate instead.
```
<ngx-daterangepicker-material
[locale]="{applyLabel: 'Go'}"
[timePicker]="true"
[timePicker24Hour]="true"
[timePickerSeconds]="true"
(choosedDate)="selectedDateRangeChange($event)">
</ngx-daterangepicker-material>
```

**Comment by alua1612** [comment]
hello @fetrarij , how to get selected dates without clicking apply button? like with reactive forms

**Comment by fetrarij** [comment]
Hello @alua1612  How about using [autoApply]="true"

**Comment by yogeshk732** [comment]
how to display the selected values in inline mode

**Comment by czalaira** [comment]
Hi I put my the inline mode into a dialog and passing data using event. How can I put a default value from the parent to modal and apply into the daterange picker as selected date?
![image](https://user-images.githubusercontent.com/27965104/74911480-aa745680-53f7-11ea-8f8b-16aa368bdc3a.png)

**Comment by akvaliya** [comment]
Any resolution to this? I am also facing same issue. I want to open inline date picker with pre-selected dates

**Comment by czalaira** [comment]
> Any resolution to this? I am also facing same issue. I want to open inline date picker with pre-selected dates/range

Hi I found a way without using ngModel.

See image below.

![image](https://user-images.githubusercontent.com/27965104/75331039-05f18900-58bd-11ea-8c8d-553bcb5a2adc.png)

**Comment by adrielzarate** [comment]
My solution, with @ViewChild too ...
```
updateDatepicker() {
    this.selected = {
        startDate: this.startDate,
        endDate: this.endDate
    };
    this.datepicker.setStartDate(this.selected.startDate);
    this.datepicker.setEndDate(this.selected.endDate);
    this.datepicker.updateCalendars();
}
```

**Comment by GuillaumeMMM** [comment]
Thanks for the solutions!

I still had to call `this.picker.updateView()` after setting the startDate and endDate.

**Comment by HFTSxRiDeR** [comment]
```
export class SomeComponent implements AfterViewInit {
  @ViewChild(DaterangepickerComponent, { static: false }) datePicker: DaterangepickerComponent;

  @Input() selectedPeriod: {
    startDate: Moment,
    endDate: Moment,
  };

  constructor(private changeDetector: ChangeDetectorRef) {}

  ngAfterViewInit(): void {
    this.datePicker.setStartDate(this.selectedPeriod.startDate);
    this.datePicker.setEndDate(this.selectedPeriod.endDate);
    this.datePicker.updateView();
    this.changeDetector.detectChanges();
  }
}
```
